# Generated by Django 6.1 on 2026-08-23 08:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('kra_pin', models.CharField(max_length=50, unique=True)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=255)),
                ('physical_address', models.TextField(blank=True, null=True)),
                ('gps_coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_domain', models.CharField(max_length=100, unique=True)),
                ('subscription_tier', models.CharField(choices=[('seed', 'Seed'), ('spark', 'Spark'), ('rose', 'Rose'), ('summit', 'Summit'), ('elite', 'Elite'), ('legacy', 'Legacy')], default='seed', max_length=50)),
                ('subscription_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=50)),
                ('billing_cycle_start', models.DateField(blank=True, null=True)),
                ('public_listing', models.BooleanField(default=False)),
                ('operating_hours', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('documents', models.JSONField(blank=True, default=dict)),
                ('document_verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
