# Generated by Django 6.1 on 2026-08-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='booking_cancellation_hours',
            field=models.PositiveIntegerField(default=24, help_text='Free cancellation window in hours before booking time.'),
        ),
        migrations.AddField(
            model_name='venue',
            name='booking_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage (e.g., 20.00) or fixed amount (e.g., 1000.00).', max_digits=10),
        ),
        migrations.AddField(
            model_name='venue',
            name='booking_deposit_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', help_text='Whether deposit is a percentage of total or a fixed amount.', max_length=20),
        ),
        migrations.AddField(
            model_name='venue',
            name='currency',
            field=models.CharField(default='KES', max_length=3),
        ),
        migrations.AddField(
            model_name='venue',
            name='hire_blackout_dates',
            field=models.JSONField(blank=True, default=list, help_text='List of dates (ISO format) when the venue is not available for hire.'),
        ),
        migrations.AddField(
            model_name='venue',
            name='max_party_size',
            field=models.PositiveIntegerField(blank=True, help_text='Global maximum party size (overrides table capacity). Leave blank for no limit.', null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='min_hire_period_hours',
            field=models.PositiveIntegerField(default=4, help_text='Minimum hire duration in hours for full venue hire.'),
        ),
        migrations.AddField(
            model_name='venue',
            name='table_booking_advance_days',
            field=models.PositiveIntegerField(default=7, help_text='How many days in advance a table can be booked.'),
        ),
        migrations.AddField(
            model_name='venue',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=5),
        ),
    ]
