# Generated by Django 6.0.8 on 2026-08-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venue_booking_cancellation_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='auto_capture_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='legal_owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='legal_owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='legal_owner_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='owner_invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='owner_invitation_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='owner_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
