# Generated by Django 6.0.8 on 2026-08-28 10:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_venue_auto_capture_enabled_venue_legal_owner_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='next_billing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='trial_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VenueRefundPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancellation_policy', models.CharField(choices=[('flexible', 'Flexible'), ('moderate', 'Moderate'), ('strict', 'Strict')], default='flexible', max_length=20)),
                ('full_refund_window_hours', models.PositiveIntegerField(default=48, help_text='Hours before booking start for 100% refund')),
                ('partial_refund_window_hours', models.PositiveIntegerField(default=24, help_text='Hours before booking start for partial refund (will apply partial percentage)')),
                ('partial_refund_percentage', models.DecimalField(decimal_places=2, default=50.0, help_text='Percentage to refund during the partial window (e.g., 50.00 for 50%)', max_digits=5)),
                ('no_show_charge_percentage', models.DecimalField(decimal_places=2, default=100.0, help_text='Percentage charged for no-show (e.g., 100.00 means full charge)', max_digits=5)),
                ('venue_cancellation_refund', models.BooleanField(default=True, help_text='If venue cancels, refund 100%')),
                ('rescheduling_allowed', models.BooleanField(default=True)),
                ('rescheduling_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee for rescheduling (0 = free)', max_digits=10)),
                ('force_majeure_policy', models.TextField(blank=True, help_text='Custom policy for force majeure events', null=True)),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_policy_config', to='venues.venue')),
            ],
            options={
                'db_table': 'venue_refund_policies',
            },
        ),
        migrations.AddField(
            model_name='venue',
            name='refund_policy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_refund_policy', to='venues.venuerefundpolicy'),
        ),
    ]
