# Generated by Django 6.0.8 on 2026-08-24 17:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0002_venue_booking_cancellation_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPReputationCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('abuse_score', models.FloatField(blank=True, null=True)),
                ('is_malicious', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ip_reputation_cache',
            },
        ),
        migrations.CreateModel(
            name='SecurityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('ip_blocklist', 'IP Blocklist'), ('ip_allowlist', 'IP Allowlist'), ('rate_limit', 'Rate Limit'), ('path_restriction', 'Path Restriction'), ('method_restriction', 'Method Restriction'), ('sql_injection', 'SQL Injection'), ('xss', 'XSS'), ('path_traversal', 'Path Traversal'), ('geo_block', 'Geo Block'), ('user_agent_block', 'User-Agent Block'), ('behavioural', 'Behavioural Anomaly'), ('request_size', 'Request Size Limit'), ('role_endpoint', 'Role-Endpoint Restriction')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('enabled', models.BooleanField(default=True)),
                ('conditions', models.JSONField(default=dict, help_text='Rule-specific parameters')),
                ('description', models.TextField(blank=True, null=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'security_rules',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rule_type', models.CharField(blank=True, max_length=50, null=True)),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('unique_ips', models.PositiveIntegerField(default=0)),
                ('unique_users', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'security_analytics',
                'unique_together': {('date', 'hour', 'rule_type', 'severity')},
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('endpoint', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.TextField(blank=True, null=True)),
                ('rule_type', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('geo_country', models.CharField(blank=True, max_length=100, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to='venues.venue')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.securityrule')),
            ],
            options={
                'db_table': 'security_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='security_ev_timesta_96e9ee_idx'), models.Index(fields=['ip_address'], name='security_ev_ip_addr_286f33_idx'), models.Index(fields=['rule_type'], name='security_ev_rule_ty_3ae983_idx'), models.Index(fields=['severity'], name='security_ev_severit_dac121_idx'), models.Index(fields=['venue'], name='security_ev_venue_i_1d770a_idx'), models.Index(fields=['user'], name='security_ev_user_id_331e99_idx')],
            },
        ),
    ]
