# Generated by Django 6.1 on 2026-08-23 10:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_token', models.CharField(help_text='Unique token for anonymous session (UUID or JWT)', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('completed', 'Completed')], default='active', max_length=20)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_sessions', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(help_text='Venue where the session was initiated', on_delete=django.db.models.deletion.CASCADE, related_name='guest_sessions', to='venues.venue')),
            ],
            options={
                'db_table': 'guest_sessions',
                'ordering': ['-start_time'],
            },
        ),
    ]
