# Generated by Django 6.0.8 on 2026-08-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestsession',
            name='is_settled',
            field=models.BooleanField(default=False, help_text='Whether the guest session (and its table) is fully settled'),
        ),
        migrations.AddField(
            model_name='guestsession',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
