# Generated by Django 6.0.8 on 2026-08-24 18:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_hqnotification_read_at_and_more'),
        ('venues', '0002_venue_booking_cancellation_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_menu_categories', to='venues.venue')),
            ],
            options={
                'db_table': 'control_menu_categories',
                'ordering': ['display_order', 'name'],
                'unique_together': {('venue', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('item_type', models.CharField(choices=[('food', 'Food'), ('beverage', 'Beverage')], default='food', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('stock_count', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=5)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_items', to='control.menucategory')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_menu_items', to='venues.venue')),
            ],
            options={
                'db_table': 'control_menu_items',
                'ordering': ['display_order', 'name'],
                'unique_together': {('venue', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('options', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_modifiers', to='control.menuitem')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_modifiers', to='venues.venue')),
            ],
            options={
                'db_table': 'control_modifiers',
                'ordering': ['name'],
                'unique_together': {('venue', 'menu_item', 'name')},
            },
        ),
    ]
