# Generated by Django 6.0.8 on 2026-08-25 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_menucategory_menuitem_modifier'),
        ('venues', '0003_venue_auto_capture_enabled_venue_legal_owner_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('documents_uploaded', models.BooleanField(default=False)),
                ('owner_verified', models.BooleanField(default=False)),
                ('profile_configured', models.BooleanField(default=False)),
                ('floor_plan_configured', models.BooleanField(default=False)),
                ('menu_configured', models.BooleanField(default=False)),
                ('payment_configured', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to='venues.venue')),
            ],
            options={
                'db_table': 'control_onboarding_progress',
            },
        ),
        migrations.CreateModel(
            name='StockAlertLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_sent_at', models.DateTimeField(auto_now_add=True)),
                ('stock_count_at_alert', models.IntegerField()),
                ('threshold_at_alert', models.IntegerField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='control.menuitem')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='venues.venue')),
            ],
            options={
                'db_table': 'control_stock_alert_logs',
                'ordering': ['-alert_sent_at'],
            },
        ),
    ]
