# Generated by Django 6.0.8 on 2026-08-25 12:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_onboardingprogress_stockalertlog'),
        ('orders', '0001_initial'),
        ('venues', '0003_venue_auto_capture_enabled_venue_legal_owner_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WastageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('written_off_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wastage_logs', to=settings.AUTH_USER_MODEL)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastage_logs', to='control.menuitem')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastage_logs', to='orders.orderitem')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastage_logs', to='venues.venue')),
                ('written_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_off_wastage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'control_wastage_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('stock_count', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=5)),
                ('change_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('version_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_changes', to=settings.AUTH_USER_MODEL)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='control.menuitem')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_versions', to='venues.venue')),
            ],
            options={
                'db_table': 'control_menu_versions',
                'ordering': ['-created_at'],
                'unique_together': {('menu_item', 'version_number')},
            },
        ),
    ]
