# Generated by Django 6.0.8 on 2026-08-25 13:51

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_wastagelog_menuversion'),
        ('venues', '0003_venue_auto_capture_enabled_venue_legal_owner_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='control_men_search__52bb0a_gin'),
        ),
    ]
