# Generated by Django 6.1 on 2026-08-22 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('venues', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='venue',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='venues.venue'),
        ),
    ]
