# Generated by Django 6.0.8 on 2026-08-25 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_cashcollection_performancemetric_shifthandover'),
        ('users', '0005_permission_role_userpermission_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission_code', models.CharField(choices=[('override_cash', 'Override Cash Collection'), ('force_capture', 'Force Capture'), ('void_hold', 'Void Hold'), ('override_exit', 'Manual Override Exit'), ('suspend_table', 'Suspend Table'), ('manage_menu', 'Manage Menu'), ('manage_staff', 'Manage Staff'), ('view_reports', 'View Reports')], max_length=50)),
                ('is_granted', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granular_permissions', to='staff.staff')),
            ],
            options={
                'db_table': 'staff_granular_permissions',
                'unique_together': {('staff', 'permission_code')},
            },
        ),
    ]
