# Generated by Django 6.1 on 2026-08-23 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='venues.venue')),
            ],
            options={
                'db_table': 'zones',
                'ordering': ['name'],
                'unique_together': {('venue', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_number', models.CharField(max_length=50)),
                ('max_capacity', models.PositiveIntegerField(default=4)),
                ('current_headcount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('cleaning', 'Cleaning'), ('suspended', 'Suspended')], default='available', max_length=20)),
                ('qr_code', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique QR code identifier for this table', unique=True)),
                ('qr_code_label', models.CharField(blank=True, help_text="Human-readable label for the QR code (e.g., 'Table 1')", max_length=100, null=True)),
                ('table_type', models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('booth', 'Booth'), ('outdoor', 'Outdoor')], default='regular', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('reservation_status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('held', 'Held')], default='available', max_length=20)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='venues.venue')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='tables.zone')),
            ],
            options={
                'db_table': 'tables',
                'ordering': ['table_number'],
                'unique_together': {('venue', 'table_number')},
            },
        ),
    ]
