# Generated by Django 6.0.8 on 2026-08-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, help_text='Higher value = higher priority (0=normal)'),
        ),
    ]
