# Generated by Django 6.0.8 on 2026-08-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='reassigned_from_host',
            field=models.BooleanField(default=False, help_text='True if this item was reassigned from the host to a guest for self‑payment'),
        ),
    ]
