# Generated by Django 6.1 on 2026-08-24 03:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
        ('venues', '0002_venue_booking_cancellation_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days_of_week', models.JSONField(default=list, help_text="List of days this shift applies to (e.g., ['monday', 'tuesday'])")),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='venues.venue')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='tables.zone')),
            ],
            options={
                'db_table': 'shifts',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.shift')),
            ],
            options={
                'db_table': 'shift_staff',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('waiter', 'Waiter'), ('chef', 'Chef'), ('bartender', 'Bartender'), ('security', 'Security'), ('receptionist', 'Receptionist'), ('manager', 'Manager'), ('owner', 'Owner'), ('admin', 'Admin'), ('support', 'Support')], max_length=50)),
                ('staff_qr', models.UUIDField(default=uuid.uuid4, editable=False, help_text='QR code for scan-in/scan-out', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='tables.zone')),
                ('shifts', models.ManyToManyField(related_name='staff_members', through='staff.ShiftStaff', to='staff.shift')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='venues.venue')),
            ],
            options={
                'db_table': 'staff',
                'ordering': ['user__full_name'],
            },
        ),
        migrations.AddField(
            model_name='shiftstaff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan_in_time', models.DateTimeField()),
                ('scan_out_time', models.DateTimeField(blank=True, null=True)),
                ('cash_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('scan_in_device', models.CharField(blank=True, max_length=255, null=True)),
                ('scan_out_device', models.CharField(blank=True, max_length=255, null=True)),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=20)),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_attendances', to='staff.staff')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='staff.shift')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='staff.staff')),
            ],
            options={
                'db_table': 'staff_attendance',
                'ordering': ['-scan_in_time'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='shiftstaff',
            unique_together={('staff', 'shift')},
        ),
    ]
