# Generated by Django 6.0.8 on 2026-08-25 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_sessions', '0001_initial'),
        ('staff', '0001_initial'),
        ('tables', '0001_initial'),
        ('venues', '0003_venue_auto_capture_enabled_venue_legal_owner_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('guest_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_collections', to='guest_sessions.guestsession')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_collections', to='staff.staff')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_collections', to='tables.table')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_collections', to='venues.venue')),
            ],
            options={
                'db_table': 'staff_cash_collections',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_turnaround_minutes', models.FloatField(default=0)),
                ('satisfaction_score', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='staff.staff')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='venues.venue')),
            ],
            options={
                'db_table': 'staff_performance_metrics',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.CharField(blank=True, max_length=100, null=True)),
                ('tables_transferred', models.PositiveIntegerField(default=0)),
                ('handed_over_at', models.DateTimeField(auto_now_add=True)),
                ('from_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers_from', to='staff.staff')),
                ('to_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers_to', to='staff.staff')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='venues.venue')),
            ],
            options={
                'db_table': 'staff_shift_handovers',
                'ordering': ['-handed_over_at'],
            },
        ),
    ]
