# Generated by Django 6.0.8 on 2026-08-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_cashcollection_performancemetric_shifthandover'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='busy_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
    ]
