# Generated by Django 6.1 on 2026-08-23 12:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest_sessions', '0001_initial'),
        ('tables', '0001_initial'),
        ('venues', '0002_venue_booking_cancellation_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(max_length=255)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField()),
                ('event_start_time', models.TimeField()),
                ('event_end_time', models.TimeField(blank=True, null=True)),
                ('max_capacity', models.PositiveIntegerField()),
                ('ticket_sales_start', models.DateTimeField()),
                ('ticket_sales_end', models.DateTimeField()),
                ('door_policy', models.TextField(blank=True, null=True)),
                ('flyer_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('checked_in_count', models.PositiveIntegerField(default=0)),
                ('total_tickets_sold', models.PositiveIntegerField(default=0)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_fee_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='venues.venue')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-event_date', '-event_start_time'],
            },
        ),
        migrations.CreateModel(
            name='TicketTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier_name', models.CharField(max_length=100)),
                ('tier_description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_limit', models.PositiveIntegerField()),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('is_vip', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tiers', to='events.event')),
                ('reserved_table', models.ForeignKey(blank=True, help_text='Table reserved for VIP bundle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_tiers', to='tables.table')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tiers', to='venues.venue')),
            ],
            options={
                'db_table': 'ticket_tiers',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_code', models.CharField(max_length=100, unique=True)),
                ('ticket_qr', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('manual_exit_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_digital', models.BooleanField(default=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_in_time', models.DateTimeField(blank=True, null=True)),
                ('exited', models.BooleanField(default=False)),
                ('exited_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('purchased', 'Purchased'), ('checked_in', 'Checked In'), ('exited', 'Exited'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='purchased', max_length=20)),
                ('purchase_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event')),
                ('guest_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='guest_sessions.guestsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='venues.venue')),
                ('ticket_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.tickettier')),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['-purchase_time'],
            },
        ),
    ]
