# Generated by Django 6.0.8 on 2026-08-25 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0001_initial'),
        ('venues', '0003_venue_auto_capture_enabled_venue_legal_owner_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['is_deleted'], name='hq_request__is_dele_447ffe_idx'),
        ),
    ]
