# Generated by Django 6.0.8 on 2026-08-25 13:46

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0002_requestlog_deleted_at_requestlog_is_deleted_and_more'),
        ('venues', '0003_venue_auto_capture_enabled_venue_legal_owner_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='hq_request__search__b54ffd_gin'),
        ),
    ]
