# Generated by Django 6.1 on 2026-08-23 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest_sessions', '0001_initial'),
        ('tables', '0001_initial'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_occupancy', models.PositiveIntegerField(default=2)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='venues.venue')),
            ],
            options={
                'db_table': 'room_types',
                'unique_together': {('venue', 'room_type')},
            },
        ),
        migrations.CreateModel(
            name='VenueHiring',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('renter_name', models.CharField(max_length=255)),
                ('renter_phone', models.CharField(max_length=20)),
                ('renter_email', models.EmailField(max_length=254)),
                ('hire_date', models.DateField()),
                ('hire_start_time', models.TimeField()),
                ('hire_end_time', models.TimeField()),
                ('hire_duration', models.CharField(max_length=50)),
                ('hire_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_status', models.CharField(choices=[('not_required', 'Not Required'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='not_required', max_length=20)),
                ('hire_qr', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hire_rules', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_in_time', models.DateTimeField(blank=True, null=True)),
                ('checked_out', models.BooleanField(default=False)),
                ('checked_out_time', models.DateTimeField(blank=True, null=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hirings', to='venues.venue')),
            ],
            options={
                'db_table': 'venue_hiring',
                'ordering': ['-hire_date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_type', models.CharField(choices=[('table', 'Table Reservation'), ('room', 'Hotel Room'), ('hire', 'Venue Hire')], max_length=20)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('party_size', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_qr', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_in_time', models.DateTimeField(blank=True, null=True)),
                ('checked_out', models.BooleanField(default=False)),
                ('checked_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('guest_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='guest_sessions.guestsession')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tables.table')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='venues.venue')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='explore.roomtype')),
                ('venue_hiring', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='explore.venuehiring')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-booking_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('available_rooms', models.PositiveIntegerField()),
                ('total_rooms', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='explore.roomtype')),
            ],
            options={
                'db_table': 'room_availability',
                'unique_together': {('room_type', 'date')},
            },
        ),
    ]
