# Generated by Django 6.0.8 on 2026-08-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_ratingsummary_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('none', 'No Refund'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='none', help_text='Current refund status for this booking', max_length=20),
        ),
    ]
