# Generated by Django 6.1 on 2026-08-23 11:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '__first__'),
        ('explore', '0001_initial'),
        ('guest_sessions', '0001_initial'),
        ('orders', '__first__'),
        ('venues', '0002_venue_booking_cancellation_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway_provider', models.CharField(choices=[('daraja', 'M-Pesa Daraja'), ('flutterwave', 'Flutterwave'), ('pesapal', 'Pesapal'), ('paystack', 'Paystack')], max_length=50)),
                ('merchant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('consumer_key', models.TextField(blank=True, help_text='Encrypted Consumer Key', null=True)),
                ('consumer_secret', models.TextField(blank=True, help_text='Encrypted Consumer Secret', null=True)),
                ('passkey', models.TextField(blank=True, help_text='Encrypted Passkey', null=True)),
                ('shortcode', models.CharField(blank=True, help_text='Paybill or Till number', max_length=50, null=True)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('failed', 'Failed')], default='inactive', max_length=20)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_config', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Payment Gateway Config',
                'verbose_name_plural': 'Payment Gateway Configs',
                'db_table': 'payment_gateway_configs',
            },
        ),
        migrations.CreateModel(
            name='PreAuthHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('declared_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hold_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('captured', 'Captured'), ('voided', 'Voided'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('mpesa', 'M-Pesa')], max_length=20)),
                ('gateway_reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_token', models.TextField(blank=True, help_text='Tokenized payment reference', null=True)),
                ('hold_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('capture_time', models.DateTimeField(blank=True, null=True)),
                ('void_time', models.DateTimeField(blank=True, null=True)),
                ('guest_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_auth_holds', to='guest_sessions.guestsession')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_auth_holds', to='venues.venue')),
            ],
            options={
                'db_table': 'pre_auth_holds',
                'ordering': ['-hold_time'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('hold', 'Pre-Authorization Hold'), ('capture', 'Capture'), ('void', 'Void'), ('top_up', 'Top Up'), ('refund', 'Refund'), ('payment', 'Direct Payment'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('cash', 'Cash')], max_length=20)),
                ('gateway_reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_response_code', models.CharField(blank=True, max_length=50, null=True)),
                ('gateway_response_message', models.TextField(blank=True, null=True)),
                ('transaction_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('transaction_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='explore.booking')),
                ('guest_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='guest_sessions.guestsession')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.order')),
                ('pre_auth_hold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.preauthhold')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='events.ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='venues.venue')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-transaction_time'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('signature', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='venues.venue')),
            ],
            options={
                'db_table': 'webhook_logs',
                'ordering': ['-received_at'],
            },
        ),
    ]
