# Generated by Django 6.0.8 on 2026-08-28 10:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_booking_refund_status'),
        ('payments', '0002_transaction_gateway_latency_ms_and_more'),
        ('venues', '0004_venue_next_billing_date_venue_trial_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_refunded',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount refunded so far', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='refund_status',
            field=models.CharField(choices=[('none', 'No Refund'), ('partial', 'Partial Refund'), ('full', 'Full Refund')], default='none', help_text='Status of any refund applied to this transaction', max_length=20),
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('venue_cancelled', 'Venue Cancelled'), ('venue_failed_service', 'Venue Failed to Provide Service'), ('customer_cancellation', 'Customer Changed Mind'), ('technical_issue', 'Technical Issue / Double Charge'), ('other', 'Other')], max_length=50)),
                ('classification', models.CharField(choices=[('venue_fault', 'Venue Fault'), ('nou_fault', 'N.O.U. Fault'), ('gateway_issue', 'Payment Gateway Issue'), ('customer_cancellation', 'Customer Cancellation')], max_length=50)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='explore.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_refunds', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='payments.transaction')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='venues.venue')),
            ],
            options={
                'db_table': 'refund_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gateway_reference_id', models.CharField(max_length=255)),
                ('gateway_response_code', models.CharField(blank=True, max_length=50, null=True)),
                ('gateway_response_message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('original_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_transactions', to='payments.transaction')),
                ('refund_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_transactions', to='payments.refundrequest')),
            ],
            options={
                'db_table': 'refund_transactions',
                'ordering': ['-processed_at'],
            },
        ),
    ]
